### ISSUE TITLE
Christmas Coding Challenge 2023!

### ISSUE THREAD

**Issue by arzucaner** [nverbic/christmas_coding_challenge_2023#25]
I am delighted to inform you that your repository has been reviewed as part of the Christmas Coding Challenge 2023, and you have earned the certificate!

Congratulations on this achievement!

**Comment by nverbic** [comment]
Dear Arzu,

Thank you so much for organizing this challenge and supporting us through
it. It has been a great experience! Looking forward to the next one :-)

Kind regards

Nevena

**Comment by nverbic** [comment]
Thank you so much @arzucaner for organizing this challenge and supporting us through it. It has been a great experience! Looking forward to the next one :-)

**Comment by arzucaner** [comment]
Thank you very much for your  comment
